# Generated by Django 2.1.5 on 2019-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
    ]
