# Generated by Django 2.1.5 on 2020-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
