# Generated by Django 2.1.5 on 2020-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200102_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
    ]
