# Generated by Django 2.2.5 on 2019-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='image_url',
            field=models.ImageField(default='abc.jpg', upload_to='team_logo'),
        ),
    ]
