# Generated by Django 2.2.5 on 2019-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teams_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='image_url',
            field=models.ImageField(default='team_logo/code.jpg', upload_to='team_logo'),
        ),
    ]
