# Generated by Django 2.1.5 on 2019-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191218_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_A', models.CharField(max_length=100)),
                ('Team_B', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi')], max_length=10)),
            ],
            options={
                'db_table': 'Match',
            },
        ),
    ]
