# Generated by Django 2.1.5 on 2019-12-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Match')),
            ],
            options={
                'db_table': 'Schedule_Match',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('KOLKATA', 'Kolkata'), ('CHENNAI', 'Chennai'), ('DELHI', 'Delhi'), ('MUMBAI', 'Mumbai'), ('KANPUR', 'Kanpur'), ('BANGALORE', 'Bangalore'), ('CUTTACK', 'Cuttack'), ('MOHALI', 'Mohali'), ('VISAKHAPATNAM', 'Visakhapatnam'), ('HYDERABAD', 'Hyderabad'), ('INDORE', 'Indore'), ('NAGPUR', 'Nagpur'), ('PUNE', 'Pune'), ('RAJKOT', 'Rajkot'), ('RANCHI', 'Ranchi'), ('DHARAMSHALA', 'Dharamshala'), ('GUWAHATI', 'Guwahati'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('DEHRADUN', 'Dehradun'), ('LUCKNOW', 'Lucknow')], max_length=20)),
            ],
            options={
                'db_table': 'Stadium',
            },
        ),
        migrations.AddField(
            model_name='schedule_match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Stadium'),
        ),
    ]
