# Generated by Django 2.1.5 on 2019-12-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191226_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='language',
        ),
    ]
