# Generated by Django 2.1.5 on 2019-12-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191227_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_match',
            name='Team_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teams'),
        ),
        migrations.AlterField(
            model_name='schedule_match',
            name='Team_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_B', to='myapp.Teams'),
        ),
    ]
