# Generated by Django 2.2.5 on 2019-12-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('myapp', '0011_auto_20191227_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=4)),
                ('booked_date', models.DateTimeField(auto_now=True)),
                ('temp_allocated', models.CharField(default='True', max_length=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Schedule_Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
            options={
                'db_table': 'Seats',
            },
        ),
    ]
