# Generated by Django 2.1.5 on 2019-12-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('myapp', '0012_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=2)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Seats', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(default='', max_length=10)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Schedule_Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
