# Generated by Django 2.1.5 on 2019-12-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bank_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Seats',
            new_name='seats',
        ),
    ]
